/**
 * llamenos-core bridge module.
 *
 * This module re-exports the UniFFI-generated bindings from the llamenos-core
 * Rust crate. The Rust library provides all cryptographic primitives:
 *
 * - ECIES encryption/decryption (secp256k1 + XChaCha20-Poly1305)
 * - BIP-340 Schnorr signatures
 * - HKDF key derivation
 * - PBKDF2 PIN-based key wrapping
 * - Nostr keypair management (nsec/npub encoding)
 * - Domain-separated crypto labels
 *
 * On iOS, this uses Swift bindings generated by UniFFI.
 * On Android, this uses Kotlin bindings generated by UniFFI.
 *
 * See ~/projects/llamenos-core for the Rust source.
 * See docs/RUST_INTEGRATION.md for build and binding generation instructions.
 */

// UniFFI bindings will be imported here once the native module is built.
// Example (post-integration):
//
// import { LlamenosCore } from "llamenos-core";
// export const core = new LlamenosCore();

export const CORE_AVAILABLE = false;
